### ISSUE TITLE
How many epochs did you use to generate this model ?

### ISSUE THREAD

**Issue by Hager-s** [nipponjo/tts-arabic-pytorch#11]

**Comment by nipponjo** [comment]
Hello, I can't remember exactly, but I think that after about 20k iterations, i.e. 80-100 epochs, I didn't notice any larger improvements. I used the pretrained [TACOTRON2_WAVERNN_CHAR_LJSPEECH](https://pytorch.org/audio/stable/generated/torchaudio.pipelines.TACOTRON2_WAVERNN_CHAR_LJSPEECH.html#tacotron2-wavernn-char-ljspeech) weights for training the Tacotron2.
