### ISSUE TITLE
No CUDA - New torch.nn.utils.parametrizations.weight_norm

### ISSUE THREAD

**Issue by imGameNinja** [nipponjo/tts-arabic-pytorch#13]
\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
Traceback (most recent call last):
\app.py", line 13, in <module>
    tts_manager = TTSManager('app/static')
---
Python310\lib\site-packages\torch\serialization.py", line 258, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by nipponjo** [comment]
Hi, thank you for making me aware of this. I would have to make a few changes to make it work on CPU, but I will only be able to do that in about a week. For the time being, you could use this Colab notebook:

https://colab.research.google.com/drive/1UzbdyXXalB0XCRK68pw6yPJcFRaM5ONF

**Comment by imGameNinja** [comment]
I do know your PHD Works , I have tested it , but the cpu is Important . I tried the test.py and the app.py with the same results , thanks in Advance for the CPU version, Good luck

**Comment by imGameNinja** [comment]
[
![CUDA Snap132](https://github.com/nipponjo/tts-arabic-pytorch/assets/65451209/28782f8e-e8a4-4d41-8630-8f78ad959eb2)
](url)

i also tried my CUDA settings , with same error

**Comment by imGameNinja** [comment]
hi i hope you are ok , please update me with the new version on CPU
also tried this    

python app.py
Python310\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
\app.py", line 13, in <module>
    tts_manager = TTSManager('app/static')

**Comment by imGameNinja** [comment]
Hi , Doctor 

any Updates ?

**Comment by nipponjo** [comment]
Hi, I have made some changes, so that the models run on CPU if they have not been pushed to the GPU. Have you tried running the `test.ipynb` notebook with `use_cuda_if_available` set to True/False?
