### ISSUE TITLE
How can I implement the code with different dataset 

### ISSUE THREAD

**Issue by zaynabmu** [nipponjo/tts-arabic-pytorch#2]
hello, 

first, thank you for amazing repository that very lack in such language like Arabic  , I have question : can I train the model with different dataset rather than Arabic speech corpus?   if yes could you please help me with steps that I should change in the code 

thank you in advance.

**Comment by nipponjo** [comment]
Hello,
you can certainly train on other datasets. What exactly you have to change, will probably depend on your dataset. In case you want to train on multiple speakers: I have added a speaker embedding to the model and fine-tuned it, such that speaker_id=0 is trained on the "Arabic speech corpus". You can try to train the other ids on other voices. The state-dict can be found [here](https://drive.google.com/file/d/19zJmu4oHnTs6q6dGQrLdqYsbZcyoJWCz/view?usp=share_link). I have attached the relevant files.

[test_ms.py.txt](https://github.com/nipponjo/tts-arabic-tacotron2/files/10075315/test_ms.py.txt)
[train_ms.py.txt](https://github.com/nipponjo/tts-arabic-tacotron2/files/10075317/train_ms.py.txt)
[nawar_ms.yaml.txt](https://github.com/nipponjo/tts-arabic-tacotron2/files/10075318/nawar_ms.yaml.txt)
[networks_ms.py.txt](https://github.com/nipponjo/tts-arabic-tacotron2/files/10075319/networks_ms.py.txt)
