### ISSUE TITLE
Vocoder

### ISSUE THREAD

**Issue by bluehybrid** [nipponjo/tts-arabic-pytorch#5]
I am asking about the vocoder should I use the vocoder that you mention like download it or there for new dataset I should change the vocoder

**Comment by FahadAlbukhari** [comment]
I have the same question do I have to make new hifigan-asc-v1 when I am trying new dataset?

**Comment by nipponjo** [comment]
Hello,
I also had this question. A few weeks ago I finetuned the pretrained hifigan `universal-v1` checkpoint to the dataset and found that it improves the results. The finetuning didn't take long (only 300-500 batches or 5 minutes) and, therefore, I recommend it. I have written a little script that makes finetuning on a custom dataset easier and attached it here.
 
[hifigan-finetune.zip](https://github.com/nipponjo/tts-arabic-pytorch/files/11471743/hifigan-finetune.zip)

**Comment by FahadAlbukhari** [comment]
Thank you for your quick response, I really appreciate you getting back to me so soon.

**Comment by FahadAlbukhari** [comment]
It seem that there is file missing named utils

hifigan-finetune\hifigan-finetune\hifigan\models.py", line 6, in <module>
    from utils import init_weights, get_padding
ModuleNotFoundError: No module named 'utils'

**Comment by nipponjo** [comment]
Right, that can be commented out. Here is another version.
[hifigan-finetune.zip](https://github.com/nipponjo/tts-arabic-pytorch/files/11485012/hifigan-finetune.zip)

**Comment by bluehybrid** [comment]
how can I get init_weights that is not defined and get_padding also ?

you commented the line that imported it and if I removed it there is no file called utils 

Traceback (most recent call last):
  File "finetune.py", line 132, in <module>
    generator = Generator(h).to(device)
  File "/home/hammad/Downloads/hifigan-finetune (1)/hifigan-finetune/hifigan/models.py", line 97, in __init__
    self.resblocks.append(resblock(h, ch, k, d))
  File "/home/hammad/Downloads/hifigan-finetune (1)/hifigan-finetune/hifigan/models.py", line 25, in __init__
    self.convs1.apply(init_weights)
NameError: name 'init_weights' is not defined

thank you

**Comment by nipponjo** [comment]
Hello, I think this version shouldn't cause this problem:
[hifigan-finetune.zip](https://github.com/nipponjo/tts-arabic-pytorch/files/11855904/hifigan-finetune.zip)
