### ISSUE TITLE
AttributeError: 'float' object has no attribute 'items'

### ISSUE THREAD

**Issue by FahadAlbukhari** [nipponjo/tts-arabic-pytorch#7]
Hello,

First and foremost, thank you for an incredible repository that is sorely lacking in a language like Arabic. I have a problem. I got this error when I created a new dataset.  this error occur when i have more than 7 line in train_phon.txt. please help.

python train.py
[==============================] 100.0%
[==============================] 100.0%
Epoch: 0
C:\Users\alghr\Dev\Python\tts-arabic-pytorch\lib\site-packages\torch\functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:867.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
loss: 48.50394821166992, grad_norm: 27.04533576965332
Traceback (most recent call last):
  File "train.py", line 207, in <module>
    main()
  File "train.py", line 195, in main
    training_loop(model,
  File "train.py", line 102, in training_loop
    writer.add_training_data(loss.item(), grad_norm.item(),
  File "C:\Users\alghr\Dev\Python\tts-arabic-pytorch\arabic\utils\logging.py", line 12, in add_training_data
    for k, v in meta.items():
AttributeError: 'float' object has no attribute 'items'

**Comment by nipponjo** [comment]
Hello,
a while ago I changed the loss function, so the train.py script doesn't work anymore. Sorry for the inconvenience, I will fix this when I have time. The updated training scripts can be found in the scripts/ folder for the tacotron2 (tc2) and fastpitch (fp) model. The _adv mean that an additional adversarial loss is used.

**Comment by FahadAlbukhari** [comment]
Thank you for your quick response—I really appreciate. By a while do you mean 2 weeks. I will try the tacotron2 (tc2). I notice the error occur when i have more than 7 line in train_phon.txt.
